### ISSUE TITLE
dcg and number_chars & atom_chars

### ISSUE THREAD

**Issue by cduret** [jburse/jekejeke-devel#18]
Hello,
When I try to output some result from  number_chars or atom_chars into a DCG statement I have an error.

My program so far
```
:- use_module(library(standard/dcg)).

:- set_prolog_flag(double_quotes, chars).

value_(Value) -->
  { integer(Value),
    number_chars(Value, Value_Char) },
  Value_Char.
value_(Value) -->
  { atom(Value),
    atom_chars(Value, Value_Char) },
  Value_Char.

  run(Value, R) :-
    phrase(value_(Value), R).
```
My queries
```
Jekejeke Prolog 4, Runtime Library 1.4.4 (26. mai 2020)
(c) 1985-2020, XLOG Technologies GmbH, Switzerland
?- run(128, R).
Error: Undefined or inaccesible predicate '.'/4.
	'.'/4
	value_/3
	run/2
?- run(toto, R).
Error: Undefined or inaccesible predicate '.'/4.
	'.'/4
	run/2
```

If I pass my variables `Value_Char` through an array id predicate
```
arr_id([], []).
arr_id([X | Y], [X | R]) :-
  arr_id(Y, R).
```
it is working and returning the right answers.

**Comment by jburse** [comment]
This is an unfortunate side effect, that the Prolog text dcg
was first an unnamed module and is now a named module.

WIll push a fix, which will also switch DCG to new body
indexing, making the translation more simple. Here is a preview:

![grafik](https://user-images.githubusercontent.com/5411487/86606744-b2005a80-bfa8-11ea-8aeb-a0966c7a62f0.png)

**Comment by jburse** [comment]
Hi,

Was testing just published [interpreter.jar](https://github.com/jburse/jekejeke-devel/releases/tag/v1.4.5). I added a cut in the test code:

value_(Value) -->
  { integer(Value),
    number_chars(Value, Value_Char) }, !, 
  Value_Char.

I now get as expected, without a lingering choice point:

```
Jekejeke Prolog 4, Laufzeitbibliothek 1.4.6 (9. August 2020)

?- run(128, R).
R = ['1', '2', '8']

?- run(toto, R).
R = [t, o, t, o]
```
