### ISSUE TITLE
Embedding a module in general

### ISSUE THREAD

**Issue by jburse** [jburse/jekejeke-devel#61]
I think this may cause the following errors when I embedd jekejeke in an OSGI application :

```
Error: Short path queries not in class paths.
        module/2
Error: Short path sql_statement not in class paths.
        module/2
...
```
The interpreter does work ok but these errors are printed I don't know why

_Originally posted by @cduret in https://github.com/jburse/jekejeke-devel/issues/28#issuecomment-689415275_

**Comment by jburse** [comment]
If you want to embed a module, you need to have it in the class path.
If youre class path of the JVM is:

      directory1;directory2;....

And if you declare a module:

    :- module(name, []).

Then the interpreter checks whether it exists in the classpath by
an appropriate file name extension. So the above module
decaration is valid if for example:

     directory2/name.pl 

exists. You can also use a package directive, to allow modules
inside subdirectories. So if you have:

    :- package(library(subdirectory)).
    :- module(name, []).

Then the interpreter accepts for example when he finds:

     directory2/subdirectory/name.pl

**Comment by jburse** [comment]
The #28 ticket will simplify some of these things, like
allowing a package directive which is simpler, better error
handling and maybe also class path less modules:

  :- package(subdirectory).
  :- module(name, []).

Making it closer to Java. If we would also allow class path
less modules, we would move away from Java, and get
closer to SWI-Prolog. This will be also tried.

**Comment by cduret** [comment]
My source files were indeed within a subdirectory `prolog/`.

I have added the `package(library(prolog))` directive within each source file and now it works perfectly !

```
:- package(library(prolog)).

:- module(my_module, [
  ...
]).
```

thanks

**Comment by jburse** [comment]
Since you raised a new OSGI ticket, I am closing this ticket.
